spring.application.name=aws-app-s3-dw

server.port=8080

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

aws.region=${AWS_REGION:sa-east-1}
aws.s3.bucket-name=${AWS_S3_BUCKET:aws-java-class-s3-863430399807-sa-east-1-an}
aws.s3.default-prefix=${AWS_S3_PREFIX:Aula-Java/}
